### ISSUE TITLE
"Design Editor is unavailable until a successful build"

### ISSUE THREAD

**Issue by Leet3079** [Leet3079/ICS4U1a201718_FinalProject#1]
![screenshot 145](https://user-images.githubusercontent.com/33405996/33409263-84897ade-d548-11e7-8887-227287197876.png)

**Comment by Leet3079** [comment]
Re-opened android studio, all the design editors of xml files do not show

**Comment by daniel-cheung1130** [comment]
Solved by clicking clean project
